name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      working-directory: example_tool
      run: |
        poetry install
    
    - name: Lint with ruff
      working-directory: example_tool
      run: |
        poetry run ruff check .
    
    - name: Check formatting with ruff
      working-directory: example_tool
      run: |
        poetry run ruff format --check .