name: Release - example-tool

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable.publish-python.yml
    with:
      path: .
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
